# Generated by Django 4.1.5 on 2023-02-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=80)),
                ('phone', models.IntegerField(max_length=11)),
                ('address', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=80)),
                ('date', models.DateField()),
            ],
        ),
    ]
